"""Profile generation — scaffold new profile .cue files from a template.

Single + bulk generation. Phase 2 implementation uses a simple string template;
Phase 3 may switch to a Cue-native template (`cue eval --inject`) for stronger
guarantees.
"""

from __future__ import annotations

from pathlib import Path

from .paths import REPO_ROOT

PROFILES_DIR = REPO_ROOT / "profiles"
BASES_DIR = PROFILES_DIR / "bases"

# Current fleet pin — keep in sync with tools/stage3.lock.cue (deriving these
# from the lock file is a possible follow-up). Used as scaffold defaults by
# all generators and the `profile new` CLI options.
DEFAULT_MLNODE_VERSION = "0.2.13"
DEFAULT_VLLM_VERSION = "0.23.0"


_TEMPLATE = """\
// Profile: {description}
//
// Generated by `mlnode-foundry profile new` — review and tune before validating.
package profiles

import "github.com/kaitakuai/mlnode-foundry/profiles/bases"

{key}: #BaseProfile{bases_chain} & {{
\tidentity: {{
\t\taxes: {{
\t\t\tgpu:            "{gpu}"
\t\t\tmodel:          "{model}"
\t\t\tmodel_revision: "{model_revision}"{quant_axis}
\t\t}}
\t\tversion: {{
\t\t\tmlnode: "{mlnode}"
\t\t\tvllm:   "{vllm}"
\t\t\trev:    {rev}
\t\t}}
\t}}
\tmode:         "kaitakuai-base"
\t// TODO: set to "{runner_patch_suggestion}-plugin" once that patcher exists
\t// under tools/runner-patches/ (empty = no runner patch).
\trunner_patch: ""
\tenv: {{}}
\truntime_defaults: {{}}
\tdescription: "{description}"
}}
"""


def _filename(gpu: str, model: str, model_revision: str, quant: str | None) -> str:
    """Profile filename = <gpu>-<model>-<model_revision>[-<quant>].

    Must match what tools/naming.cue produces for the package name (modulo
    the 'mlnode-' prefix and tag axes) so that filename ↔ package is 1:1.
    Enforced at validation time by validate.validate_filename_matches_axes.
    """
    parts = [gpu, model, model_revision]
    if quant:
        parts.append(quant)
    return "-".join(parts)


def _key(gpu: str, model: str, model_revision: str, quant: str | None) -> str:
    return _filename(gpu, model, model_revision, quant).replace("-", "_")


def _bases_chain(gpu: str, model: str, quant: str | None) -> str:
    """Return a chain like ` & bases.B300 & bases.KIMI_INT4` for known axes.

    Only emits a base if a `profiles/bases/<name>.cue` exists. Skips unknown
    axes silently — author can add a base later.
    """
    chain_parts: list[str] = []
    candidates = [gpu.upper(), model.upper()]
    if quant:
        candidates.append(f"{model.upper()}_{quant.upper()}")
    for cand in candidates:
        # Heuristic: file naming convention bases/<lowercase>.cue exports <UPPERCASE>
        candidate_file = BASES_DIR / f"{cand.lower()}.cue"
        if candidate_file.exists():
            chain_parts.append(f" & bases.{cand}")
    return "".join(chain_parts)


def generate_profile(
    *,
    gpu: str,
    model: str,
    model_revision: str,
    quant: str | None = None,
    mlnode: str = DEFAULT_MLNODE_VERSION,
    vllm: str = DEFAULT_VLLM_VERSION,
    rev: int = 1,
) -> Path:
    """Generate a new profile .cue file. Returns path. Refuses to overwrite."""
    filename = _filename(gpu, model, model_revision, quant)
    path = PROFILES_DIR / f"{filename}.cue"
    if path.exists():
        raise FileExistsError(f"Profile already exists: {path}")
    description = f"{gpu.upper()} + {model.capitalize()}-{model_revision}"
    if quant:
        description += f" {quant.upper()}"
    description += " — generated profile, tune before use"
    content = _TEMPLATE.format(
        description=description,
        key=_key(gpu, model, model_revision, quant),
        gpu=gpu,
        model=model,
        model_revision=model_revision,
        quant_axis=(f'\n\t\t\tquant:          "{quant}"' if quant else ""),
        mlnode=mlnode,
        vllm=vllm,
        rev=rev,
        runner_patch_suggestion=(
            f"{gpu}-{model}" if quant is None else f"{gpu}-{model}-{quant}"
        ),
        bases_chain=_bases_chain(gpu, model, quant),
    )
    path.write_text(content)
    return path


def bulk_add_model(
    *,
    model: str,
    model_revision: str,
    gpus: list[str],
    quant: str | None = None,
    mlnode: str = DEFAULT_MLNODE_VERSION,
    vllm: str = DEFAULT_VLLM_VERSION,
    rev: int = 1,
) -> list[Path]:
    """Generate profiles for `model` across multiple GPUs."""
    return [
        generate_profile(
            gpu=g.strip(),
            model=model,
            model_revision=model_revision,
            quant=quant,
            mlnode=mlnode,
            vllm=vllm,
            rev=rev,
        )
        for g in gpus
        if g.strip()
    ]


def bulk_add_gpu(
    *,
    gpu: str,
    models: list[tuple[str, str]],
    mlnode: str = DEFAULT_MLNODE_VERSION,
    vllm: str = DEFAULT_VLLM_VERSION,
    rev: int = 1,
) -> list[Path]:
    """Generate profiles for `gpu` across multiple (model, revision) tuples."""
    return [
        generate_profile(
            gpu=gpu,
            model=m.strip(),
            model_revision=r.strip(),
            mlnode=mlnode,
            vllm=vllm,
            rev=rev,
        )
        for m, r in models
        if m.strip()
    ]
